package tutorial28;


// for a base class never used by itself to instatiate objects, mark it abstract
public abstract class Machine {
   private int id;

   // getter and setter code generated by going to source in eclipse and picking generate getters/setters
public int getId() {
	return id;
}

public void setId(int id) {
	this.id = id;
}
   // abstract class can have abstract methods.. forces subclass to implement the method in the subclass
   public abstract void start();

  public void run(){
	  start();
  } 
  }